name: Deploy to Netlify preview

on:
  pull_request:
    branches:
      - '**'

jobs:
  docs-preview:
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: ${{ github.head_ref }}

    steps:

      - name: Checkout seqeralabs/docs master
        uses: actions/checkout@v4
        with:
          repository: seqeralabs/docs
          ref: chris-poc-nextflow
          path: docs-repo

      - name: Update fetch-docs-oss.mjs to use PR branch for nextflow
        run: |
          sed -i "/repo: 'nextflow'/,/\}/s/branch: '[^']*'/branch: '${PR_BRANCH}'/" docs-repo/internal/fetch-docs-oss.mjs

      - name: Remove nextflow_repo directory
        run: rm -rf docs-repo/nextflow_docs/nextflow_repo

      - name: Install dependencies
        working-directory: docs-repo
        run: npm install

      - name: Build documentation
        env:
          EXCLUDE_CHANGELOG: false 
          EXCLUDE_PLATFORM_ENTERPRISE: false 
          EXCLUDE_PLATFORM_CLOUD: false 
          EXCLUDE_PLATFORM_API: true
          EXCLUDE_PLATFORM_OPENAPI: true
          EXCLUDE_MULTIQC: true 
          EXCLUDE_NEXTFLOW: false 
          EXCLUDE_FUSION: true 
          EXCLUDE_WAVE: true
        working-directory: docs-repo
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Deploy Preview with Netlify CLI
        run: netlify deploy --dir=./docs-repo/build --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }} --message="Preview deploy from GitHub Actions"
